name: Tests
on:
  push:
    branches:
      - '**'
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ShellCheck
        run: shellcheck ${{ github.workspace }}/bin/check-token-expiration.sh
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Token Expiration
        uses: ./
        with:
          expiration: '2024-12-01'
          token: ${{ secrets.API_TOKEN }}
          token-name: 'action-token-expiration test token'
          warn-days: 30
          error-early: true
      - name: Test Non-expiring Token
        uses: ./
        with:
          expiration: '0000-00-00'
          token: ${{ secrets.GH_TOKEN }}
          token-name: 'action-token-expiration autotag token'